from alembic import context
from sqlalchemy import create_engine
from sqlalchemy.pool import NullPool

from app.core.config import get_settings
from app.db.base import Base

# The initial schema uses reviewed SQL (domains/routines are not autogenerated).
# Import future Base models here before autogenerating their migrations.
target_metadata = Base.metadata
settings = get_settings()
url = settings.database_url()


def include_name(name, type_, parent_names):
    """Never autogenerate deletions of Supabase or SQL-managed unmapped objects."""
    if type_ == "schema":
        return name in (None, "dms")
    if type_ == "table":
        return parent_names["schema_qualified_table_name"] in target_metadata.tables
    return True


if context.is_offline_mode():
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        compare_type=True,
        include_schemas=True,
        include_name=include_name,
        version_table_schema="public",
    )
    with context.begin_transaction():
        context.run_migrations()
else:
    engine = create_engine(url, poolclass=NullPool, connect_args={"prepare_threshold": None})
    with engine.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            include_schemas=True,
            include_name=include_name,
            version_table_schema="public",
        )
        with context.begin_transaction():
            context.run_migrations()
    engine.dispose()
